on:
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]
  merge_group:
  workflow_dispatch:

name: Check semver breakage

jobs:
  cargo-semver-check:
    runs-on: ubuntu-latest

    # Skip if PR is labelled as breaking change
    if: ${{ ! contains(github.event.pull_request.labels.*.name, 'breaking change') }}

    steps:
      - uses: actions/checkout@v4
      - name: Bonus run with main
        continue-on-error: true
        run: |
          cargo install --git https://github.com/obi1kenobi/cargo-semver-checks.git --branch main cargo-semver-checks
          cargo semver-checks --manifest-path defmt-03/ --default-features
      - name: Print Logs
        continue-on-error: true
        run: cat /tmp/report-*.toml
      - name: Bonus metadata
        run: |
          cd defmt-03
          cargo metadata --no-deps --format-version=1 > ./output.json
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          if-no-files-found: error
          path: |
            ./defmt-03/output.json
